import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Card, Empty, Field, Header, Screen } from "@/components/ui";
import { colors } from "@/constants/colors";
import { formatDate } from "@/lib/format";
import { supabase } from "@/lib/supabase";

type ActivityItem={id:number;actor_id:string|null;action:string;metadata:Record<string,string>;created_at:string};type ProfileName={id:string;display_name:string};
const verbs:Record<string,string>={"daily_report.submitted":"گزارش ثبت کرد","daily_task.created":"کار روزانه اضافه کرد","daily_task.completed":"کار روزانه را انجام داد","report.approved":"گزارش را تأیید کرد","report.rejected":"گزارش را رد کرد","report.revision_requested":"درخواست اصلاح گزارش ثبت کرد","report.deleted":"گزارش را حذف کرد","repair_intake.created":"تعمیرات مشتری را ثبت کرد","repair_item.delivery_requested":"لینک تحویل مشتری ساخت","technician_job.created":"دستگاه را به تعمیرکار ارجاع داد","employee.created":"حساب کارمند ساخت"};
export default function ActivityScreen(){const[items,setItems]=useState<ActivityItem[]>([]);const[profiles,setProfiles]=useState<ProfileName[]>([]);const[query,setQuery]=useState("");const load=useCallback(async()=>{const[{data:activity},{data:names}]=await Promise.all([supabase.from("activity_logs").select("id, actor_id, action, metadata, created_at").order("created_at",{ascending:false}).limit(100),supabase.from("profiles").select("id, display_name")]);setItems((activity as ActivityItem[]|null)??[]);setProfiles((names as ProfileName[]|null)??[]);},[]);useFocusEffect(useCallback(()=>{void load();},[load]));const nameMap=useMemo(()=>new Map(profiles.map((item)=>[item.id,item.display_name])),[profiles]);const visible=items.filter((item)=>`${nameMap.get(item.actor_id??"")??"سامانه"} ${verbs[item.action]??"فعالیت ثبت کرد"} ${JSON.stringify(item.metadata)}`.includes(query));return <Screen><Header title="فعالیت‌ها" subtitle="رویدادهای واقعی ثبت‌شده سامانه" action={<Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={24}/></Pressable>}/><Card><Field label="جست‌وجو" value={query} onChangeText={setQuery}/></Card>{visible.length===0?<Card><Empty title="فعالیتی ثبت نشده" description="تاریخچه عملیات اینجا نمایش داده می‌شود."/></Card>:<Card>{visible.map((item)=><View key={item.id} style={styles.item}><View style={styles.icon}><Ionicons name="pulse-outline" size={20} color={colors.primary}/></View><View style={styles.copy}><Text style={styles.text}><Text style={styles.name}>{nameMap.get(item.actor_id??"")??"سامانه"}</Text> {verbs[item.action]??"فعالیت ثبت کرد"}</Text><Text style={styles.date}>{formatDate(item.created_at)}</Text></View></View>)}</Card>}</Screen>}
const styles=StyleSheet.create({item:{flexDirection:"row-reverse",gap:10,paddingVertical:11,borderBottomWidth:1,borderBottomColor:colors.border},icon:{width:39,height:39,borderRadius:13,backgroundColor:colors.surfaceMuted,alignItems:"center",justifyContent:"center"},copy:{flex:1,alignItems:"flex-end"},text:{textAlign:"right",writingDirection:"rtl"},name:{fontWeight:"900"},date:{fontSize:10,color:colors.muted,marginTop:4}});
