import { Ionicons } from "@expo/vector-icons";
import { Link, router, useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Card, Empty, Field, Header, Screen } from "@/components/ui";
import { colors } from "@/constants/colors";
import { supabase } from "@/lib/supabase";
import type { Customer, RepairItem } from "@/lib/types";

export default function CustomersScreen(){const[customers,setCustomers]=useState<Customer[]>([]);const[items,setItems]=useState<RepairItem[]>([]);const[query,setQuery]=useState("");const[refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>{setRefreshing(true);const[{data:customerData},{data:itemData}]=await Promise.all([supabase.from("customers").select("id, full_name, phone, created_at").order("created_at",{ascending:false}),supabase.from("customer_repair_items").select("id, customer_id, intake_id, item_name, quantity, status, received_at, delivered_at")]);setCustomers((customerData as Customer[]|null)??[]);setItems((itemData as RepairItem[]|null)??[]);setRefreshing(false);},[]);useFocusEffect(useCallback(()=>{void load();},[load]));const visible=customers.filter((item)=>`${item.full_name} ${item.phone??""}`.includes(query));return <Screen refreshing={refreshing} onRefresh={load}><Header title="مشتریان" subtitle="پرونده وسایل دریافتی و تحویل‌شده" action={<Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={24}/></Pressable>}/><Card><Field label="جست‌وجوی مشتری" value={query} onChangeText={setQuery}/></Card>{visible.length===0?<Card><Empty title="مشتری وجود ندارد" description="مشتری هنگام ثبت تعمیرات اضافه می‌شود." icon="people-outline"/></Card>:visible.map((customer)=>{const customerItems=items.filter((item)=>item.customer_id===customer.id);const active=customerItems.filter((item)=>item.status==="received").length;return <Link key={customer.id} href={{pathname:"/customer/[id]",params:{id:customer.id}}} asChild><Pressable><Card style={styles.customer}><View style={styles.avatar}><Text>{customer.full_name.slice(0,1)}</Text></View><View style={styles.copy}><Text style={styles.name}>{customer.full_name}</Text><Text style={styles.meta}>{customer.phone??"بدون شماره تماس"}</Text><Text style={styles.count}>{active} در حال تعمیر · {customerItems.length-active} تحویل‌شده</Text></View><Ionicons name="chevron-back" size={20} color={colors.muted}/></Card></Pressable></Link>;})}</Screen>}
const styles=StyleSheet.create({customer:{flexDirection:"row-reverse",alignItems:"center"},avatar:{width:50,height:50,borderRadius:16,backgroundColor:colors.surfaceMuted,alignItems:"center",justifyContent:"center"},copy:{flex:1,alignItems:"flex-end"},name:{fontWeight:"900",fontSize:16},meta:{color:colors.muted,fontSize:11,marginTop:3},count:{color:colors.success,fontSize:10,marginTop:5}});
