import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Badge, Button, Card, Empty, ErrorBanner, Field, Header, Screen, SuccessBanner } from "@/components/ui";
import { colors } from "@/constants/colors";
import { apiFetch } from "@/lib/api";
import { supabase } from "@/lib/supabase";
import type { Employee } from "@/lib/types";

export default function EmployeesScreen(){const[employees,setEmployees]=useState<Employee[]>([]);const[fullName,setFullName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[pending,setPending]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");const load=useCallback(async()=>{const{data}=await supabase.from("employees").select("id, profile_id, full_name, email, status").order("full_name");setEmployees((data as Employee[]|null)??[]);},[]);useFocusEffect(useCallback(()=>{void load();},[load]));async function create(){setError("");if(fullName.trim().length<2||!email.includes("@")||password.length<8)return setError("نام، ایمیل و رمز حداقل ۸ کاراکتری را کامل کنید.");setPending(true);try{const data=await apiFetch<{message:string}>("/api/users",{method:"POST",body:JSON.stringify({fullName,email,password})});setSuccess(data.message);setFullName("");setEmail("");setPassword("");void load();}catch(reason){setError(reason instanceof Error?reason.message:"ساخت حساب انجام نشد.");}finally{setPending(false);}}return <Screen><Header title="کارکنان" subtitle="ساخت حساب فقط با نام، ایمیل و رمز" action={<Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={24}/></Pressable>}/>{error?<ErrorBanner message={error}/>:null}{success?<SuccessBanner message={success}/>:null}<Card><Field label="نام" value={fullName} onChangeText={setFullName}/><Field label="ایمیل" value={email} onChangeText={setEmail} keyboardType="email-address" autoComplete="off"/><Field label="رمز عبور" value={password} onChangeText={setPassword} secureTextEntry autoComplete="off"/><Button title="ساخت حساب کارمند" icon="person-add-outline" onPress={create} loading={pending}/></Card>{employees.length===0?<Card><Empty title="کارمندی ثبت نشده" description="حساب‌های ساخته‌شده اینجا نمایش داده می‌شوند."/></Card>:employees.map((item)=><Card key={item.id} style={styles.employee}><View style={styles.avatar}><Text>{item.full_name.slice(0,1)}</Text></View><View style={styles.copy}><Text style={styles.name}>{item.full_name}</Text><Text style={styles.email}>{item.email}</Text></View><Badge text={item.status==="active"?"فعال":"غیرفعال"} tone={item.status==="active"?"success":"neutral"}/></Card>)}</Screen>}
const styles=StyleSheet.create({employee:{flexDirection:"row-reverse",alignItems:"center"},avatar:{width:46,height:46,borderRadius:15,backgroundColor:colors.surfaceMuted,alignItems:"center",justifyContent:"center"},copy:{flex:1,alignItems:"flex-end"},name:{fontWeight:"900"},email:{color:colors.muted,fontSize:11,marginTop:3}});
