import { Ionicons } from "@expo/vector-icons";
import { Link, useFocusEffect } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { Badge, Button, Card, Empty, ErrorBanner, Field, Header, Screen } from "@/components/ui";
import { colors } from "@/constants/colors";
import { useAuth } from "@/contexts/auth-context";
import { apiFetch } from "@/lib/api";
import { formatDate, statusLabels } from "@/lib/format";
import { supabase } from "@/lib/supabase";
import type { DailyReport, Employee } from "@/lib/types";

export default function HistoryScreen(){
  const {profile}=useAuth();const [reports,setReports]=useState<DailyReport[]>([]);const [employees,setEmployees]=useState<Employee[]>([]);const [query,setQuery]=useState("");const [employeeFilter,setEmployeeFilter]=useState("");const [locationFilter,setLocationFilter]=useState("");const [error,setError]=useState("");const [refreshing,setRefreshing]=useState(false);
  const load=useCallback(async()=>{setRefreshing(true);try{const [{data:reportData},{data:employeeData}]=await Promise.all([supabase.from("daily_reports").select("id, employee_id, report_date, start_time, end_time, location, work_summary, status, submitted_at, deleted_at").is("deleted_at",null).order("report_date",{ascending:false}).order("submitted_at",{ascending:false}),supabase.from("employees").select("id, profile_id, full_name, email, status").eq("status","active")]);setReports((reportData as DailyReport[]|null)??[]);setEmployees((employeeData as Employee[]|null)??[]);}catch{setError("دریافت گزارش‌ها انجام نشد.");}finally{setRefreshing(false);}},[]);useFocusEffect(useCallback(()=>{void load();},[load]));
  const names=useMemo(()=>new Map(employees.map((item)=>[item.id,item.full_name])),[employees]);const locations=[...new Set(reports.map((item)=>item.location).filter(Boolean))];const visible=reports.filter((report)=>{const text=`${names.get(report.employee_id)??""} ${report.location} ${report.work_summary}`.toLowerCase();return(!query||text.includes(query.toLowerCase()))&&(!employeeFilter||report.employee_id===employeeFilter)&&(!locationFilter||report.location===locationFilter);});
  async function remove(report:DailyReport){Alert.alert("حذف گزارش","این گزارش از فهرست حذف شود؟",[{text:"انصراف",style:"cancel"},{text:"حذف",style:"destructive",onPress:async()=>{try{await apiFetch(`/api/reports/daily/${report.id}/review`,{method:"DELETE"});setReports((items)=>items.filter((item)=>item.id!==report.id));}catch(reason){setError(reason instanceof Error?reason.message:"حذف انجام نشد.");}}}]);}
  return <Screen refreshing={refreshing} onRefresh={load}><Header title="سوابق گزارش" subtitle={profile?.role==="admin"?"همه گزارش‌های ثبت‌شده":"فقط گزارش‌های ثبت‌شده شما"} action={profile?.role==="admin"?<Link href="/review" asChild><Pressable><Ionicons name="shield-checkmark-outline" size={25}/></Pressable></Link>:undefined}/>{error?<ErrorBanner message={error}/>:null}<Card><Field label="جست‌وجو" value={query} onChangeText={setQuery}/>{profile?.role==="admin"?<><Text style={styles.filterTitle}>فیلتر کارمند</Text><View style={styles.chips}><FilterChip title="همه" active={!employeeFilter} onPress={()=>setEmployeeFilter("")}/>{employees.map((item)=><FilterChip key={item.id} title={item.full_name} active={employeeFilter===item.id} onPress={()=>setEmployeeFilter(item.id)}/>)}</View><Text style={styles.filterTitle}>فیلتر محل</Text><View style={styles.chips}><FilterChip title="همه" active={!locationFilter} onPress={()=>setLocationFilter("")}/>{locations.map((item)=><FilterChip key={item} title={item} active={locationFilter===item} onPress={()=>setLocationFilter(item)}/>)}</View></>:null}</Card>{visible.length===0?<Card><Empty title="گزارشی وجود ندارد" description="گزارش‌های ثبت‌شده در این صفحه نمایش داده می‌شوند."/></Card>:visible.map((report)=><Card key={report.id}><View style={styles.reportHead}><Badge text={statusLabels[report.status]} tone={report.status==="approved"?"success":report.status==="submitted"?"blue":"warning"}/><View style={styles.reportAuthor}><Text style={styles.author}>{names.get(report.employee_id)??profile?.display_name}</Text><Text style={styles.date}>{formatDate(report.report_date)}</Text></View></View><Text style={styles.summary}>{report.work_summary}</Text><View style={styles.meta}><Text>{report.location}</Text><Ionicons name="location-outline" size={18} color={colors.muted}/></View>{report.start_time&&report.end_time?<View style={styles.meta}><Text>{report.start_time.slice(0,5)} تا {report.end_time.slice(0,5)}</Text><Ionicons name="time-outline" size={18} color={colors.muted}/></View>:null}{profile?.role==="admin"?<Button title="حذف گزارش" icon="trash-outline" tone="danger" onPress={()=>remove(report)}/>:null}</Card>)}</Screen>;
}
function FilterChip({title,active,onPress}:{title:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,active&&styles.chipActive]}><Text style={active&&styles.chipTextActive}>{title}</Text></Pressable>}
const styles=StyleSheet.create({filterTitle:{fontWeight:"800",fontSize:12,textAlign:"right"},chips:{flexDirection:"row-reverse",flexWrap:"wrap",gap:7},chip:{paddingHorizontal:11,paddingVertical:8,borderRadius:12,backgroundColor:colors.surfaceMuted},chipActive:{backgroundColor:colors.primary},chipTextActive:{color:"#fff",fontWeight:"800"},reportHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},reportAuthor:{alignItems:"flex-end"},author:{fontWeight:"900"},date:{fontSize:10,color:colors.muted,marginTop:3},summary:{textAlign:"right",writingDirection:"rtl",lineHeight:23,color:colors.text,fontWeight:"700"},meta:{flexDirection:"row-reverse",gap:6,alignItems:"center"}});
