import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { Pressable, Share, StyleSheet, Text, View } from "react-native";
import { Button, Card, Empty, ErrorBanner, Field, Header, Screen, SuccessBanner } from "@/components/ui";
import { colors } from "@/constants/colors";
import { apiFetch } from "@/lib/api";
import { faNumber } from "@/lib/format";
import { supabase } from "@/lib/supabase";
import type { Customer } from "@/lib/types";

type Item = { id: string; itemName: string; quantity: string };

export default function MaintenanceScreen() {
  const [customers,setCustomers]=useState<Customer[]>([]); const [customerId,setCustomerId]=useState(""); const [addingCustomer,setAddingCustomer]=useState(false); const [fullName,setFullName]=useState(""); const [phone,setPhone]=useState(""); const [items,setItems]=useState<Item[]>([{id:"first",itemName:"",quantity:"1"}]); const [query,setQuery]=useState(""); const [pending,setPending]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [confirmationUrl,setConfirmationUrl]=useState("");
  const load=useCallback(async()=>{const {data}=await supabase.from("customers").select("id, full_name, phone, created_at").order("full_name");setCustomers((data as Customer[]|null)??[]);},[]); useFocusEffect(useCallback(()=>{void load();},[load]));
  const visible=customers.filter((customer)=>customer.full_name.includes(query)||customer.phone?.includes(query));
  function updateItem(id:string,values:Partial<Item>){setItems((current)=>current.map((item)=>item.id===id?{...item,...values}:item));}
  async function submit(){setError("");setSuccess("");if((addingCustomer&&fullName.trim().length<2)||(!addingCustomer&&!customerId))return setError("مشتری را انتخاب یا اضافه کنید.");if(items.some((item)=>item.itemName.trim().length<2||Number(item.quantity)<1))return setError("نام وسیله و تعداد را کامل کنید.");setPending(true);try{const data=await apiFetch<{confirmationUrl:string|null;message:string}>("/api/maintenance-intakes",{method:"POST",body:JSON.stringify({customerId:addingCustomer?null:customerId,newCustomer:addingCustomer?{fullName,phone}:null,items:items.map((item)=>({itemName:item.itemName,quantity:Number(item.quantity)}))})});setSuccess(data.message);setConfirmationUrl(data.confirmationUrl??"");setCustomerId("");setFullName("");setPhone("");setItems([{id:`${Date.now()}`,itemName:"",quantity:"1"}]);void load();}catch(reason){setError(reason instanceof Error?reason.message:"ثبت تعمیرات انجام نشد.");}finally{setPending(false);}}
  return <Screen><Header title="ثبت تعمیرات" subtitle="مشتری، وسیله و تعداد" />{success?<SuccessBanner message={success}/>:null}{error?<ErrorBanner message={error}/>:null}{confirmationUrl?<Card><Text style={styles.sectionTitle}>لینک تأیید مشتری آماده است</Text><Text style={styles.sectionSub}>لینک را برای مشتری ارسال کنید تا دریافت وسیله را تأیید کند.</Text><Button title="ارسال لینک" icon="share-social-outline" onPress={()=>void Share.share({message:confirmationUrl})}/></Card>:null}<Card><View style={styles.switch}><Pressable onPress={()=>setAddingCustomer(false)} style={[styles.switchButton,!addingCustomer&&styles.switchActive]}><Text style={!addingCustomer&&styles.switchActiveText}>انتخاب مشتری</Text></Pressable><Pressable onPress={()=>setAddingCustomer(true)} style={[styles.switchButton,addingCustomer&&styles.switchActive]}><Text style={addingCustomer&&styles.switchActiveText}>مشتری جدید</Text></Pressable></View>{addingCustomer?<><Field label="نام مشتری" value={fullName} onChangeText={setFullName}/><Field label="شماره تماس (اختیاری)" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/></>:<><Field label="جست‌وجوی مشتری" value={query} onChangeText={setQuery}/><View style={styles.customerList}>{visible.length===0?<Empty title="مشتری پیدا نشد" description="از گزینه مشتری جدید استفاده کنید."/>:visible.slice(0,8).map((customer)=><Pressable key={customer.id} onPress={()=>setCustomerId(customer.id)} style={[styles.customer,customerId===customer.id&&styles.customerSelected]}><Ionicons name={customerId===customer.id?"checkmark-circle":"person-circle-outline"} size={22} color={customerId===customer.id?colors.success:colors.muted}/><View><Text style={styles.customerName}>{customer.full_name}</Text>{customer.phone?<Text style={styles.customerPhone}>{customer.phone}</Text>:null}</View></Pressable>)}</View></>}</Card><Card><View style={styles.itemsHead}><Button title="افزودن وسیله" icon="add" tone="secondary" onPress={()=>setItems((current)=>[...current,{id:`${Date.now()}-${Math.random()}`,itemName:"",quantity:"1"}])}/><View><Text style={styles.sectionTitle}>وسایل دریافتی</Text><Text style={styles.sectionSub}>{faNumber(items.length)} مورد</Text></View></View>{items.map((item,index)=><View key={item.id} style={styles.item}><View style={styles.itemHead}>{items.length>1?<Pressable onPress={()=>setItems((current)=>current.filter((value)=>value.id!==item.id))}><Ionicons name="trash-outline" color={colors.danger} size={20}/></Pressable>:<View/>}<Text style={styles.itemTitle}>وسیله {faNumber(index+1)}</Text></View><Field label="نام قطعه یا دستگاه" value={item.itemName} onChangeText={(value)=>updateItem(item.id,{itemName:value})}/><Field label="تعداد" value={item.quantity} onChangeText={(value)=>updateItem(item.id,{quantity:value.replace(/\D/g,"").slice(0,3)})} keyboardType="numeric"/></View>)}</Card><Button title="ثبت و ساخت لینک تأیید" icon="checkmark-circle-outline" onPress={submit} loading={pending}/></Screen>;
}

const styles=StyleSheet.create({switch:{flexDirection:"row-reverse",backgroundColor:colors.surfaceMuted,borderRadius:14,padding:4},switchButton:{flex:1,padding:10,alignItems:"center",borderRadius:11},switchActive:{backgroundColor:colors.primary},switchActiveText:{color:"#fff",fontWeight:"800"},customerList:{gap:7},customer:{flexDirection:"row-reverse",alignItems:"center",gap:9,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:11},customerSelected:{backgroundColor:colors.successSoft,borderColor:colors.success},customerName:{fontWeight:"800",textAlign:"right"},customerPhone:{fontSize:10,color:colors.muted,textAlign:"right",marginTop:2},itemsHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},sectionTitle:{fontSize:16,fontWeight:"900",textAlign:"right"},sectionSub:{fontSize:11,color:colors.muted,textAlign:"right",marginTop:3},item:{borderTopWidth:1,borderTopColor:colors.border,paddingTop:13,gap:11},itemHead:{flexDirection:"row",justifyContent:"space-between"},itemTitle:{fontWeight:"900"}});
