import { Ionicons } from "@expo/vector-icons";
import * as ImagePicker from "expo-image-picker";
import { useFocusEffect } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Button, Card, ErrorBanner, Field, Header, Screen, SuccessBanner } from "@/components/ui";
import { JalaliPicker, type JalaliValue } from "@/components/jalali-picker";
import { colors } from "@/constants/colors";
import { useAuth } from "@/contexts/auth-context";
import { apiFetch } from "@/lib/api";
import { faNumber } from "@/lib/format";
import { isValidTime, normalizeTime } from "@/lib/jalali";
import { supabase } from "@/lib/supabase";
import type { Employee } from "@/lib/types";

type Expense = { id: string; description: string; amount: string; image: ImagePicker.ImagePickerAsset | null };
const steps = ["زمان و محل", "شرح فعالیت", "مخارج"];

export default function ReportScreen() {
  const { profile, employee } = useAuth();
  const [step, setStep] = useState(0); const [date, setDate] = useState<JalaliValue>(null); const [startTime, setStartTime] = useState(""); const [endTime, setEndTime] = useState(""); const [location, setLocation] = useState(""); const [summary, setSummary] = useState(""); const [collaborators, setCollaborators] = useState<Employee[]>([]); const [selected, setSelected] = useState<string[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [pending, setPending] = useState(false);
  useFocusEffect(useCallback(() => { void supabase.from("employees").select("id, profile_id, full_name, email, status").eq("status","active").order("full_name").then(({data}) => setCollaborators(((data as Employee[]|null)??[]).filter((item)=>item.id!==employee?.id || item.full_name.trim()==="میلاد"))); }, [employee?.id]));
  const progress = useMemo(()=>`${faNumber(step+1)} از ${faNumber(steps.length)}`,[step]);
  function validate() { if (step===0 && (!date || !isValidTime(startTime) || !isValidTime(endTime) || location.trim().length<2)) return "تاریخ، ساعت ورود و خروج و محل کار را کامل کنید."; if(step===1&&summary.trim().length<2)return "شرح فعالیت را وارد کنید."; if(step===2&&expenses.some((item)=>item.description.trim().length<2||Number(item.amount.replace(/\D/g,""))<=0))return "شرح و مبلغ همه مخارج را کامل کنید."; return ""; }
  async function next() { const message=validate(); if(message)return setError(message); setError(""); if(step<2)return setStep((v)=>v+1); if(!date)return; setPending(true); try { const form=new FormData(); form.append("report",JSON.stringify({year:String(date.year),month:String(date.month),day:String(date.day),startTime,endTime,location,collaboratorIds:selected,workSummary:summary})); form.append("expenses",JSON.stringify(expenses.map((item)=>({description:item.description,amount:item.amount})))); expenses.forEach((item,index)=>{if(item.image)form.append(`invoice-${index}`,{uri:item.image.uri,name:item.image.fileName??`invoice-${index}.jpg`,type:item.image.mimeType??"image/jpeg"} as never);}); await apiFetch("/api/daily-reports",{method:"POST",body:form}); setSuccess("گزارش با موفقیت ثبت شد."); setDate(null);setStartTime("");setEndTime("");setLocation("");setSummary("");setSelected([]);setExpenses([]);setStep(0); } catch(reason){setError(reason instanceof Error?reason.message:"ثبت گزارش انجام نشد.");} finally{setPending(false);} }
  function addExpense(){setExpenses((items)=>[...items,{id:`${Date.now()}-${Math.random()}`,description:"",amount:"",image:null}]);}
  function updateExpense(id:string, values:Partial<Expense>){setExpenses((items)=>items.map((item)=>item.id===id?{...item,...values}:item));}
  async function pickImage(id:string){const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return setError("برای انتخاب فاکتور اجازه دسترسی به تصاویر لازم است.");const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],quality:.82,allowsEditing:false});if(!result.canceled)updateExpense(id,{image:result.assets[0]});}
  return <Screen><Header title="ثبت گزارش" subtitle={`مرحله ${progress} · ${steps[step]}`} />{success?<SuccessBanner message={success}/>:null}{error?<ErrorBanner message={error}/>:null}<View style={styles.progress}>{steps.map((title,index)=><View key={title} style={styles.progressItem}><View style={[styles.progressDot,index<=step&&styles.progressActive]}>{index<step?<Ionicons name="checkmark" size={15} color="#fff"/>:<Text style={index<=step?styles.progressActiveText:undefined}>{faNumber(index+1)}</Text>}</View><Text style={[styles.progressLabel,index===step&&styles.progressLabelActive]}>{title}</Text></View>)}</View>
    <Card>{step===0&&<><View style={styles.owner}><View style={styles.ownerIcon}><Ionicons name="person-outline" size={21}/></View><View><Text style={styles.ownerLabel}>ثبت‌کننده گزارش</Text><Text style={styles.ownerName}>{profile?.display_name}</Text></View></View><Text style={styles.label}>تاریخ شمسی</Text><JalaliPicker value={date} onChange={setDate}/><View style={styles.row}><View style={styles.half}><Field label="ساعت ورود" value={startTime} onChangeText={(value)=>setStartTime(normalizeTime(value))} keyboardType="numeric" /></View><View style={styles.half}><Field label="ساعت خروج" value={endTime} onChangeText={(value)=>setEndTime(normalizeTime(value))} keyboardType="numeric" /></View></View><Field label="محل انجام کار" value={location} onChangeText={setLocation}/><View style={styles.collabHead}><Text style={styles.optional}>{selected.length?`${faNumber(selected.length)} نفر`:"اختیاری"}</Text><Text style={styles.label}>همکاران همراه</Text></View><View style={styles.chips}>{collaborators.map((item)=>{const active=selected.includes(item.id);return <Pressable key={item.id} onPress={()=>setSelected((ids)=>active?ids.filter((id)=>id!==item.id):[...ids,item.id])} style={[styles.chip,active&&styles.chipActive]}><Ionicons name={active?"checkmark-circle":"ellipse-outline"} size={18} color={active?colors.success:colors.muted}/><Text>{item.full_name}</Text></Pressable>;})}</View></>}
      {step===1&&<><View style={styles.formIcon}><Ionicons name="document-text-outline" size={31} color={colors.primary}/></View><Field label="فعالیت‌های انجام‌شده" value={summary} onChangeText={setSummary} multiline/><Text style={styles.hint}>فعالیت‌ها را کوتاه، روشن و به ترتیب انجام ثبت کنید.</Text></>}
      {step===2&&<><View style={styles.expenseHead}><Button title="افزودن هزینه" icon="add" tone="secondary" onPress={addExpense}/><View><Text style={styles.sectionTitle}>مخارج</Text><Text style={styles.sectionSub}>این بخش اجباری نیست.</Text></View></View>{expenses.length===0?<View style={styles.expenseEmpty}><Ionicons name="receipt-outline" size={34} color={colors.muted}/><Text style={styles.sectionTitle}>هزینه‌ای اضافه نشده</Text><Text style={styles.sectionSub}>در صورت نیاز یک هزینه اضافه کنید.</Text></View>:expenses.map((item,index)=><View key={item.id} style={styles.expense}><View style={styles.expenseTitle}><Pressable onPress={()=>setExpenses((items)=>items.filter((value)=>value.id!==item.id))}><Ionicons name="trash-outline" size={20} color={colors.danger}/></Pressable><Text>هزینه {faNumber(index+1)}</Text></View><Field label="برای چه موردی؟" value={item.description} onChangeText={(value)=>updateExpense(item.id,{description:value})}/><Field label="مبلغ (تومان)" value={item.amount} onChangeText={(value)=>updateExpense(item.id,{amount:value.replace(/\D/g,"").slice(0,12)})} keyboardType="numeric"/><Button title={item.image?"تغییر تصویر فاکتور":"افزودن تصویر فاکتور"} icon="image-outline" tone="secondary" onPress={()=>pickImage(item.id)}/>{item.image?<Text style={styles.fileName}>{item.image.fileName??"تصویر انتخاب شد"}</Text>:null}</View>)}</>}
    </Card><View style={styles.actions}>{step>0?<Button title="قبلی" icon="arrow-forward" tone="secondary" onPress={()=>{setError("");setStep((v)=>v-1);}} style={styles.half}/>:<View style={styles.half}/>}<Button title={step===2?"ثبت گزارش":"ادامه"} icon={step===2?"checkmark":"arrow-back"} onPress={next} loading={pending} style={styles.half}/></View>
  </Screen>;
}

const styles=StyleSheet.create({progress:{flexDirection:"row-reverse",justifyContent:"space-between"},progressItem:{alignItems:"center",gap:5,flex:1},progressDot:{width:29,height:29,borderRadius:10,backgroundColor:colors.surfaceMuted,alignItems:"center",justifyContent:"center"},progressActive:{backgroundColor:colors.primary},progressActiveText:{color:"#fff",fontWeight:"900"},progressLabel:{fontSize:10,color:colors.muted},progressLabelActive:{color:colors.primary,fontWeight:"900"},owner:{flexDirection:"row-reverse",alignItems:"center",gap:10,backgroundColor:colors.surfaceMuted,borderRadius:15,padding:12},ownerIcon:{width:40,height:40,borderRadius:13,backgroundColor:colors.surface,alignItems:"center",justifyContent:"center"},ownerLabel:{fontSize:10,color:colors.muted,textAlign:"right"},ownerName:{fontWeight:"900",textAlign:"right",marginTop:2},label:{fontWeight:"800",fontSize:13,color:colors.text,textAlign:"right"},row:{flexDirection:"row-reverse",gap:10},half:{flex:1},collabHead:{flexDirection:"row",justifyContent:"space-between"},optional:{color:colors.muted,fontSize:11},chips:{flexDirection:"row-reverse",flexWrap:"wrap",gap:8},chip:{flexDirection:"row-reverse",gap:6,alignItems:"center",paddingHorizontal:11,paddingVertical:9,borderWidth:1,borderColor:colors.border,borderRadius:13},chipActive:{backgroundColor:colors.successSoft,borderColor:colors.success},formIcon:{width:58,height:58,borderRadius:18,backgroundColor:colors.surfaceMuted,alignSelf:"center",alignItems:"center",justifyContent:"center"},hint:{color:colors.muted,fontSize:11,textAlign:"right",lineHeight:20},expenseHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},sectionTitle:{fontWeight:"900",fontSize:16,textAlign:"right"},sectionSub:{color:colors.muted,fontSize:11,textAlign:"right",marginTop:3},expenseEmpty:{alignItems:"center",padding:28,gap:7},expense:{borderTopWidth:1,borderTopColor:colors.border,paddingTop:14,gap:12},expenseTitle:{flexDirection:"row",justifyContent:"space-between"},fileName:{fontSize:11,color:colors.success,textAlign:"center"},actions:{flexDirection:"row-reverse",gap:10}});
