import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import { useCallback, useState } from "react";
import { Pressable, Share, StyleSheet, Text, View } from "react-native";
import { Badge, Button, Card, Empty, ErrorBanner, Header, Screen } from "@/components/ui";
import { colors } from "@/constants/colors";
import { apiFetch } from "@/lib/api";
import { faNumber, formatDate, statusLabels } from "@/lib/format";
import { supabase } from "@/lib/supabase";
import type { Customer, RepairItem } from "@/lib/types";

export default function CustomerDetailScreen(){const{id}=useLocalSearchParams<{id:string}>();const[customer,setCustomer]=useState<Customer|null>(null);const[items,setItems]=useState<RepairItem[]>([]);const[error,setError]=useState("");const[refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>{if(!id)return;setRefreshing(true);const[{data:customerData},{data:itemData}]=await Promise.all([supabase.from("customers").select("id, full_name, phone, created_at").eq("id",id).maybeSingle(),supabase.from("customer_repair_items").select("id, customer_id, intake_id, item_name, quantity, status, received_at, delivered_at").eq("customer_id",id).order("received_at",{ascending:false})]);setCustomer(customerData as Customer|null);setItems((itemData as RepairItem[]|null)??[]);setRefreshing(false);},[id]);useFocusEffect(useCallback(()=>{void load();},[load]));async function delivery(item:RepairItem){try{const data=await apiFetch<{confirmationUrl:string}>(`/api/customers/${id}/items/${item.id}`,{method:"PATCH"});await Share.share({message:data.confirmationUrl});}catch(reason){setError(reason instanceof Error?reason.message:"ساخت لینک انجام نشد.");}}return <Screen refreshing={refreshing} onRefresh={load}><Header title={customer?.full_name??"پرونده مشتری"} subtitle={customer?.phone??""} action={<Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={24}/></Pressable>}/>{error?<ErrorBanner message={error}/>:null}{items.length===0?<Card><Empty title="وسیله‌ای ثبت نشده" description="وسایل مشتری پس از پذیرش در این صفحه نمایش داده می‌شوند."/></Card>:items.map((item)=><Card key={item.id}><View style={styles.head}><Badge text={statusLabels[item.status]} tone={item.status==="delivered"?"success":"warning"}/><View><Text style={styles.title}>{item.item_name}</Text><Text style={styles.meta}>{faNumber(item.quantity)} عدد · {formatDate(item.received_at)}</Text></View></View>{item.status==="received"?<Button title="ساخت لینک تأیید تحویل" icon="share-social-outline" onPress={()=>delivery(item)}/>:<View style={styles.delivered}><Ionicons name="checkmark-circle" size={20} color={colors.success}/><Text>تحویل مشتری شده است</Text></View>}</Card>)}</Screen>}
const styles=StyleSheet.create({head:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{fontWeight:"900",fontSize:17,textAlign:"right"},meta:{fontSize:11,color:colors.muted,textAlign:"right",marginTop:4},delivered:{flexDirection:"row-reverse",gap:7,alignItems:"center",backgroundColor:colors.successSoft,padding:12,borderRadius:13}});
